### PR TITLE
load-image-from-buffer

### PR DESCRIPTION
**Pull request by kamisori**

### CODE REVIEW

**Comment by kamisori** [comment]
egh... sorry i didnt see the other pull request, but i would argue using a buffer is better than a string

**Comment by sogaiu** [comment]
Just to be clear, you mean [this PR](https://github.com/janet-lang/jaylib/pull/59), right?

**Comment by kamisori** [comment]
aye, that one. i added a bmp header generator function for ease of use

**Comment by kamisori** [comment]
also added tests for both functions

**Pull request merged**
